# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - arm_group_controller
    - chassis_group_controller

  arm_group_controller:
    type: FollowJointTrajectory
    joints:
      - joint5
      - joint6
      - joint7
      - joint8
      - joint9
      - joint10
      - joint11
  chassis_group_controller:
    type: FollowJointTrajectory
    joints:
      - joint1
      - joint2
      - joint3
      - joint4